{% set version = "2.1.0" %}

package:
  name: bob.ip.facedetect
  version: {{ version }}

source:
  fn: bob.ip.facedetect-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.ip.facedetect/bob.ip.facedetect-{{ version }}.zip
  md5: 43985e483a119b498a3584fc9b5567cf

build:
  entry_points:
    - collect_training_data.py = bob.ip.facedetect.script.collect_training_data:main
    - extract_training_features.py = bob.ip.facedetect.script.extract_training_features:main
    - train_detector.py = bob.ip.facedetect.script.train_detector:main
    - validate_detector.py = bob.ip.facedetect.script.validate_detector:main
    - detect_faces.py = bob.ip.facedetect.script.detect_faces:main
    - evaluate_detections.py = bob.ip.facedetect.script.evaluate:main
    - plot_froc.py = bob.ip.facedetect.script.plot_froc:main
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.learn.boosting
    - bob.ip.base
    - bob.ip.draw
    - bob.ip.color
    - bob.io.image
    - boost 1.61.*
    - pkg-config

  run:
    - python
    - bob.learn.boosting
    - bob.ip.base
    - bob.ip.draw
    - bob.ip.color
    - bob.io.image
    - boost 1.61.*

test:
  commands:
    - collect_training_data.py --help
    - extract_training_features.py --help
    - train_detector.py --help
    - validate_detector.py --help
    - detect_faces.py --help
    - evaluate_detections.py --help
    - plot_froc.py --help
    - nosetests -sv bob.ip.facedetect

  imports:
    - bob
    - bob.ip
    - bob.ip.facedetect

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Face Detection using a Cascade of Boosted LBP Features

extra:
  recipe-maintainers:
    - 183amir
